# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56c6afd67d0072177258cb3ed0b037210ea2fc601027dc68029a3a029247d2ed1747e3c0888bc32065f19a9d7398d6eab89c65684beba7524b3d0325933757ec

test:
  secret_key_base: 72fe3f98a97cc1ca5eea7b239cf8afbe4a478b34499c397f72b6c6208761b1807ea112e8445851eaec302a203309234eb2535dc4e2b0b0bb068ea05a1e6bdfe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
